### ISSUE TITLE
`nanobox run` panics if networking fails

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#20]
Ubuntu Linux

nanobox.log
```
2015-11-06 09:58:20 FATAL [commands/imagesUpdate] server.Update() failed -  - Post http://172.16.3.133:1757/image-update: dial tcp 172.16.3.133:1757: getsockopt: no route to host
2015-11-06 09:58:20 FATAL [util/server/mist/mist] mist.NewRemoteClient() failed -  - dial tcp 172.16.3.133:1445: getsockopt: no route to host
```

```
$ nanobox  run
+> Creating a nanobox
   - +> Updating nanobox docker images...
A fatal error occurred (See ~/.nanobox/nanobox.log for details). Exiting...
A fatal error occurred (See ~/.nanobox/nanobox.log for details). Exiting...
panic: close of closed channel

goroutine 17 [running]:
github.com/nanobox-io/nanobox/config.Fatal(0x987380, 0x38, 0xc82001af00, 0x38)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/config/log.go:51 +0x2d3
github.com/nanobox-io/nanobox/util/server/mist.connect(0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/mist/mist.go:149 +0xae
github.com/nanobox-io/nanobox/util/server/mist.Stream(0xc82001aec0, 0x3, 0x4, 0xc820100100)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/mist/mist.go:119 +0x114
github.com/nanobox-io/nanobox/util/server/mist.mist.Stream(0xc8201000e0, 0x2, 0x2, 0xc820100100)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/mist/default.go:33 +0x3f
github.com/nanobox-io/nanobox/util/server/mist.(*mist).Stream(0xb6f0e0, 0xc8201000e0, 0x2, 0x2, 0xc820100100)
  <autogenerated>:2 +0xb5
created by github.com/nanobox-io/nanobox/commands.updateImages
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/update-images.go:37 +0x198

goroutine 1 [chan receive]:
github.com/nanobox-io/nanobox/config.Fatal(0x97e200, 0x31, 0xc8201420e0, 0x64)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/config/log.go:51 +0x2fa
github.com/nanobox-io/nanobox/commands.updateImages(0x0, 0xb6f0e0, 0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/update-images.go:47 +0x260
github.com/nanobox-io/nanobox/commands.create(0x0, 0xb6f0e0, 0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/create.go:63 +0x171
github.com/nanobox-io/nanobox/commands.boot(0xb44a20, 0xb6f0e0, 0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/commands.go:127 +0x27a
github.com/spf13/cobra.(*Command).execute(0xb44a20, 0xb6f0e0, 0x0, 0x0, 0x0, 0x0)
  /Users/sdomino/godeps/src/github.com/spf13/cobra/command.go:539 +0x8bf
github.com/spf13/cobra.(*Command).Execute(0xb431c0, 0x0, 0x0)
  /Users/sdomino/godeps/src/github.com/spf13/cobra/command.go:630 +0x46a
main.main()
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/main.go:65 +0x37a

goroutine 5 [syscall]:
syscall.Syscall(0x4a, 0x3, 0x0, 0x0, 0x2a, 0x40, 0x2a)
  /usr/local/Cellar/go/1.5/libexec/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Fsync(0x3, 0x0, 0x0)
  /usr/local/Cellar/go/1.5/libexec/src/syscall/zsyscall_linux_amd64.go:492 +0x4a
os.(*File).Sync(0xc82002e048, 0x0, 0x0)
  /usr/local/Cellar/go/1.5/libexec/src/os/file_posix.go:121 +0x61
github.com/jcelliott/lumber.(*FileLogger).startOutput(0xc820080280)
  /Users/sdomino/godeps/src/github.com/jcelliott/lumber/filelog.go:119 +0x191
created by github.com/jcelliott/lumber.newFileLogger
  /Users/sdomino/godeps/src/github.com/jcelliott/lumber/filelog.go:109 +0x199

goroutine 6 [chan receive]:
github.com/jcelliott/lumber.(*FileLogger).startOutput(0xc820080380)
  /Users/sdomino/godeps/src/github.com/jcelliott/lumber/filelog.go:115 +0x6e
created by github.com/jcelliott/lumber.newFileLogger
  /Users/sdomino/godeps/src/github.com/jcelliott/lumber/filelog.go:109 +0x199

goroutine 7 [syscall]:
os/signal.loop()
  /usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
  /usr/local/Cellar/go/1.5/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [chan receive]:
github.com/jcelliott/lumber.(*FileLogger).startOutput(0xc820080500)
  /Users/sdomino/godeps/src/github.com/jcelliott/lumber/filelog.go:115 +0x6e
created by github.com/jcelliott/lumber.newFileLogger
  /Users/sdomino/godeps/src/github.com/jcelliott/lumber/filelog.go:109 +0x199

goroutine 18 [runnable]:
net.(*OpError).Error(0xc820018f50, 0x11, 0x0)
  /usr/local/Cellar/go/1.5/libexec/src/net/net.go:406
github.com/nanobox-io/nanobox/util/server/mist.connect(0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/mist/mist.go:149 +0x77
github.com/nanobox-io/nanobox/util/server/mist.Listen(0xc82000bce0, 0x2, 0x2, 0xc82000bd00, 0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/mist/mist.go:80 +0xda
github.com/nanobox-io/nanobox/util/server/mist.mist.Listen(0xc82000bce0, 0x2, 0x2, 0xc82000bd00, 0x0, 0x0)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/mist/default.go:29 +0x4b
github.com/nanobox-io/nanobox/util/server/mist.(*mist).Listen(0xb6f0e0, 0xc82000bce0, 0x2, 0x2, 0xc82000bd00, 0x0, 0x0)
  <autogenerated>:1 +0xc1
github.com/nanobox-io/nanobox/commands.updateImages.func1(0xc820102180)
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/update-images.go:42 +0xfd
created by github.com/nanobox-io/nanobox/commands.updateImages
  /Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/update-images.go:43 +0x1d8
```

**Comment by lyondhill** [comment]
Is this still happening? there is a new catch that was put in. that should have fixed this,

**Comment by glinton** [comment]
closing until seen again
