### ISSUE TITLE
mount error(115) on "nanobox run"

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#372]
While trying to `nanobox run` I get the following error:

```
λ nanobox version
Nanobox version 2.0.2 ()
λ nanobox run
Preparing environment :
  * Mounting codebase

MBrodala's password is required to mount a Windows share. (must be your Windows Live password if linked)
Password:

  ! Mounting codebase

Error   : mount: output: mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //192.168.99.1/nanobox-d5cbe4585cc247d7c24ecf7cc4048e62 on /share/d5cbe4585cc247d7c24ecf7cc4048e62/code failed: Operation now in progress
exit status 32
 err:exit status 1
Context : failed to init docker client -> failed to setup env mounts -> failed to mount the code share on the provider

Enter to continue:
```

Any idea what could be wrong?

**Comment by tylerflint** [comment]
tagging @lyondhill

**Comment by mbrodala** [comment]
More details from the `~/.nanobox/nanobox.log`:

```
2017-02-15 16:35:17 INFO  adding share in netfs for C:/Users/mbrodala/project
2017-02-15 16:35:17 INFO  adding mount in for netfs C:/Users/mbrodala/project -> /share/d5cbe4585cc247d7c24ecf7cc4048e62/code
2017-02-15 16:35:47 ERROR mount: output: mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //192.168.99.1/nanobox-d5cbe4585cc247d7c24ecf7cc4048e62 on /share/d5cbe4585cc247d7c24ecf7cc4048e62/code failed: Operation now in progress
exit status 32
 err:exit status 1
2017-02-15 16:35:47 ERROR goroutine 1 [running]:
runtime/debug.Stack(0xc04221e140, 0x133, 0x0)
  /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/debug/stack.go:24 +0x80
github.com/nanobox-io/nanobox/util.Err.log(0xc04221e140, 0x133, 0xcfb978, 0x0, 0x0)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:51 +0xd1
github.com/nanobox-io/nanobox/util.ErrorQuiet(0xca9080, 0xc0421c8f00, 0x2e, 0x2e)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:86 +0x219
github.com/nanobox-io/nanobox/util.Error(0xca9080, 0xc0421c8f00, 0xc0421c8f00, 0xc0423fd8e0)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:96 +0x5d
github.com/nanobox-io/nanobox/util.ErrorAppend(0xca9080, 0xc0421c8f00, 0xa1df3d, 0x2e, 0x0, 0x0, 0x0, 0x18, 0x0)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:119 +0x380
github.com/nanobox-io/nanobox/processors/env.Mount(0xc042098370, 0x0, 0x0)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/mount.go:42 +0x2c9
github.com/nanobox-io/nanobox/processors/env.Setup(0xc042098370, 0x0, 0x0)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/setup.go:37 +0x365
github.com/nanobox-io/nanobox/processors.Build(0xc042098370, 0x0, 0x0)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/build.go:20 +0x6d
github.com/nanobox-io/nanobox/commands.buildFn(0xcd5a00, 0xc042279e70, 0x1, 0x1)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/build.go:40 +0x4e
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0xcd5a00, 0xc042279e70, 0x1, 0x1)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:20 +0x143
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0xcd5a00, 0xc042279e40, 0x1, 0x1, 0xcd5a00, 0xc042279e40)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x444
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xcd2e00, 0x0, 0x0, 0x1)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x3df
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0xcd2e00, 0xa57b70, 0xc04224f300)
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x32
main.main()
  /home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:104 +0x253

2017-02-15 16:35:47 INFO  notifying bugsnag: mount: output: mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //192.168.99.1/nanobox-d5cbe4585cc247d7c24ecf7cc4048e62 on /share/d5cbe4585cc247d7c24ecf7cc4048e62/code failed: Operation now in progress
exit status 32
 err:exit status 1
2017-02-15 16:37:23 *LOG* Closing log now
```

**Comment by mbrodala** [comment]
Can you have a closer look at this? NB is currently unusable for me due to this.

**Comment by lyondhill** [comment]
hello mbrodala I have been looking into mouting issues and have not been able to reproduce the issue your having. It would appear there is something getting in the way of the mounting. Is there a time we can work through the issue in real time (slack) that would work for you?

**Comment by mbrodala** [comment]
This *may* be related to #365 but I'm investigating it right now. If I have the following in my `boxfile.yml`, I get the error above:

```yaml
data.chrome:
  image: selenium/standalone-chrome
```

**Comment by mbrodala** [comment]
It's weird, I cannot reproduce the issue anymore using version 2.0.2 (e89afaff3cf8a7621eba73c1ddc5b525).

I thought that the issue would show up if I have that component in my `boxfile.yml` on the first start but even that did work now.

So for now this is fixed for me.

**Comment by lyondhill** [comment]
@mbrodala we had another user who ran into this issue. After some digging we found that his firewall was stopping the vm from comunicating with his windows machine. If you run into it again lets have a look at your firewall.

**Comment by mbrodala** [comment]
Thanks for the pointer. I'll let you know when it shows up again.

**Comment by andybeak** [comment]
Sorry to necro, but I found my solution here -https://github.com/nanobox-io/nanobox/issues/462
