### ISSUE TITLE
Hooks fail with excessively large payloads

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#455]
Trying to `run` with multiple key files in `~/.ssh` breaks:

(from @petrosp in slack)

`<a huge string>` is 135732 chars long
```
2017-06-01 22:37:03 ERROR exec:Cmd:Run: 90a7d81ba8f3002aedd14099f72e7f782668aed4e35ae81084657a78db26ae2f, /opt/nanobox/hooks/user, [{"os":"darwin","provider":"docker-machine","ssh_files":{<a huge string>}]
2017-06-01 22:37:03 ERROR exec:cmd:Output: rpc error: code = 2 desc = oci runtime error: exec failed: argument list too long
, err: bad exit code(126): 
2017-06-01 22:37:03 ERROR failed to execute hook (user) on 90a7d81ba8f3002aedd14099f72e7f782668aed4e35ae81084657a78db26ae2f: util:Exec:/opt/nanobox/hooks/user: bad exit code(126): 
2017-06-01 22:37:03 ERROR goroutine 1 [running]:
runtime/debug.Stack(0xc420210140, 0x9a, 0x0)
    /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/debug/stack.go:24 +0x79
github.com/nanobox-io/nanobox/util.Err.log(0xc420210140, 0x9a, 0x949348, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:51 +0xca
github.com/nanobox-io/nanobox/util.ErrorfQuiet(0x651fa9, 0x25, 0xc420555448, 0x3, 0x3, 0x17, 0xc420085810)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:61 +0x10e
github.com/nanobox-io/nanobox/util/hookit.Exec(0xc420212b40, 0x40, 0x638c16, 0x4, 0xc4204d4000, 0x2126c, 0x638982, 0x4, 0xc4204d4000, 0x2126c, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/hookit/hookit.go:32 +0x2e6
github.com/nanobox-io/nanobox/util/hookit.DebugExec(0xc420212b40, 0x40, 0x638c16, 0x4, 0xc4204d4000, 0x2126c, 0x638982, 0x4, 0xc420478840, 0x0, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/hookit/hookit.go:38 +0x9e
github.com/nanobox-io/nanobox/processors/code.prepareBuildEnvironment(0xc420212b40, 0x40, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/code/build.go:85 +0xe7
github.com/nanobox-io/nanobox/processors/code.Build(0xc42048e0b0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/code/build.go:46 +0x2ae
github.com/nanobox-io/nanobox/processors.Build(0xc42048e0b0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/build.go:30 +0x94
github.com/nanobox-io/nanobox/commands.buildFn(0x923e00, 0xc4202fed90, 0x1, 0x1)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/build.go:40 +0x47
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0x923e00, 0xc4202fed90, 0x1, 0x1)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:20 +0x13c
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0x923e00, 0xc4202fed60, 0x1, 0x1, 0x923e00, 0xc4202fed60)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x43d
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x921200, 0x0, 0x0, 0x1)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x3d8
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0x921200, 0x694cf0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x2b
main.main()
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:117 +0x27a
```

**Comment by glinton** [comment]
This seems to be a [limitation of the kernel](https://stackoverflow.com/a/18647755) regarding how argument size, we likely don't need ever key a user has stored, perhaps there is a way to slim down what gets imported/passed to the user hook?

**Comment by petrosp** [comment]
Hey guys, in the meantime -- until this finds its way in production -- is there any way we can define a custom location where `nanobox` will be picking the keys up from, i.e. via an ENV variable?

I am also wondering if the `.git/config` file is also copied with the SSH keys? If someone has more than one SSH keys in their `~/.ssh` folder they are most probably referenced in their respective section in the `config` file.

Considering a solution where `nanobox` picks a customized ssh folder in a per-project basis, could perhaps solve the issue once a for all.

Thanks for listening!

**Comment by lyondhill** [comment]
I am going to start on a feature where you can do `nanobox configure ssh_key /path/to/folder/` or `nanobox configure ssh_key /path/to/actual/key_rsa`

with the first option it will read all keys in the folder
and the send option it will read that exact key
