### ISSUE TITLE
Can't mount code base!

### ISSUE THREAD

**Issue by kouwasi** [nanobox-io/nanobox#480]
The following situation occurs and the code base can not be mounted

The version of nanobox is version 2.1.2 (01d8252ec83bc7cc7f4ba7ce0f8a1c4a)
Windows version is Windows 10 1703 build 15063.413

```
Preparing environment :
  ! Mounting codebase
  ! Mounting codebase
  ! Mounting codebase
  ! Mounting codebase
  ! Mounting codebase

Error   : failed to add share exit status 2
Context : failed to init docker client -> failed to setup env mounts -> failed to mount the code share on the provider -> failed to add share
```

``` nanobox.log
2017-06-27 04:18:13 ERROR failed to add share exit status 2 
2017-06-27 04:18:13 ERROR goroutine 1 [running]:
runtime/debug.Stack(0xc0423e2570, 0x22, 0x0)
	/home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/debug/stack.go:24 +0x80
github.com/nanobox-io/nanobox/util.Err.log(0xc0423e2570, 0x22, 0xdbde30, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:51 +0xd1
github.com/nanobox-io/nanobox/util.ErrorQuiet(0xd66180, 0xc04230afd0, 0x13, 0x13)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:86 +0x219
github.com/nanobox-io/nanobox/util.Error(0xd66180, 0xc04230afd0, 0xc04230afd0, 0xc0421a1610)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:96 +0x5d
github.com/nanobox-io/nanobox/util.ErrorAppend(0xd66180, 0xc04230afd0, 0xa93c9f, 0x13, 0x0, 0x0, 0x0, 0x1, 0xc0421a16c8)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:119 +0x380
github.com/nanobox-io/nanobox/processors/env/share.Add(0xc0422a2e00, 0x1f, 0xc04230a9d0, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/share/add.go:22 +0x1ca
github.com/nanobox-io/nanobox/util/provider.DockerMachine.AddMount(0xc0422a2e00, 0x1f, 0xc042230a50, 0x2c, 0xc0421a1801, 0x466c7f)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/provider/dockermachine_mount.go:86 +0x5b3
github.com/nanobox-io/nanobox/util/provider.(*DockerMachine).AddMount(0xdbde30, 0xc0422a2e00, 0x1f, 0xc042230a50, 0x2c, 0xc042230a50, 0xc0420d6000)
	<autogenerated>:57 +0x7b
github.com/nanobox-io/nanobox/util/provider.AddMount(0xc0422a2e00, 0x1f, 0xc042230a50, 0x2c, 0x2, 0xc042230a50)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/provider/provider.go:289 +0x77
github.com/nanobox-io/nanobox/processors/env.Mount(0xc042084630, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/mount.go:40 +0x228
github.com/nanobox-io/nanobox/processors/env.Setup.func1(0xc0421a19d0, 0x41169f)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/setup.go:47 +0x31
github.com/nanobox-io/nanobox/util.Retry(0xc04211e060, 0x5, 0x2540be400, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/retry.go:12 +0x48
github.com/nanobox-io/nanobox/processors/env.Setup(0xc042084630, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/setup.go:50 +0x413
github.com/nanobox-io/nanobox/processors.Build(0xc042084630, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/build.go:20 +0x6d
github.com/nanobox-io/nanobox/commands.buildFn(0xd940c0, 0xc0422c6200, 0x1, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/build.go:40 +0x4e
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0xd940c0, 0xc0422c6200, 0x1, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:20 +0x143
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0xd940c0, 0xc0422c61d0, 0x1, 0x1, 0xd940c0, 0xc0422c61d0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x444
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xd914c0, 0x0, 0x0, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x3df
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0xd914c0, 0xae79f0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x32
main.main()
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:117 +0x281
```

**Comment by lyondhill** [comment]
it appears it is failing to add the share to your windows share system. can you "run as administrator" a cmd and in there run `net share`

**Comment by lyondhill** [comment]
@kouwasi did this get resolved?

**Comment by kouwasi** [comment]
@lyondhill It will not be solved
There is no change even if things shared by net share are deleted

And is it a specification that executing `nanobox destroy` does not delete items under the VM's share directory?

**Comment by lyondhill** [comment]
We currently leave shares in place because builds or deploys may require them. for production even though you may have deleted the local development environment.

**Comment by lyondhill** [comment]
when you run `net share` is your code directory listed? 

and to test if it is the mounting on the vm or just the windows share can you try adjusting the sharing to use native `nanobox config set mount-type native`. If that works then we know the sharing on windows on your machine is not working properly.

**Comment by kouwasi** [comment]
It works!
Why windows file sharing without using native?

**Comment by lyondhill** [comment]
Windows file sharing relies on windows sharing and linux mounting and the cifs adaptor. Using native uses virtual box native mounting which is all internal to virtual box. almost always works. 

What this confirms is that windows sharing is most likely the culperit. 
When using windows sharing and nanobox asks for our password to  mount, It wants to know your windows 10 password, is that the Password you provided?

**Comment by kouwasi** [comment]
I entered my password, but it did not work.
There were times when we succeeded several times, but most of them fail.
I decided to use it natively because I don't want to be disturbed by windows! :)

**Comment by lyondhill** [comment]
I will keep digging thanks for reporting kouwasi

**Comment by LeCoupa** [comment]
> when you run `net share` is your code directory listed?
> 
> and to test if it is the mounting on the vm or just the windows share can you try adjusting the sharing to use native `nanobox config set mount-type native`. If that works then we know the sharing on windows on your machine is not working properly.

Same thing happened to me on Mac
