### ISSUE TITLE
Handle `--debug` better

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#551]
Currently, passing the `--debug` flag to nanobox results in a failed hook running a second time. If the second attempt succeeds, nanobox will still try to print an error and drop into a console. This results in a panic.

The panic gets caught and printed again before getting sent off to bugsnag (which we also want to remove as we are handling this elsewhere).

Log output may look something like this:
```
2017-08-28 08:46:09 ERROR exec:Cmd:Run: 72d1f5fa287e962d3af7317e6ad8c204023a66973835292e292abee5937f7908, /opt/nanobox/hooks/setup, [{}]
2017-08-28 08:46:09 ERROR exec:cmd:Output: , err: bad exit code(1): 
2017-08-28 08:46:09 ERROR [HOOKS] failed to execute hook (setup) on 72d1f5fa287e962d3af7317e6ad8c204023a66973835292e292abee5937f7908: util:Exec:/opt/nanobox/hooks/setup: bad exit code(1): 
2017-08-28 08:46:09 ERROR goroutine 1 [running]:
runtime/debug.Stack(0xc42034c000, 0xa2, 0x0)
    /home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/debug/stack.go:24 +0x79
github.com/nanobox-io/nanobox/util.Err.log(0x0, 0x0, 0xc42034c000, 0xa2, 0x0, 0x0, 0xf9a098, 0x0, 0x0, 0x0, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:54 +0xde
github.com/nanobox-io/nanobox/util.ErrorfQuiet(0xa88eaf, 0x2d, 0xc420192f10, 0x3, 0x3, 0xabfb, 0xc420499000)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:64 +0x113
github.com/nanobox-io/nanobox/util/hookit.Exec(0xc4201d6240, 0x40, 0xa6b20b, 0x5, 0xa698fe, 0x2, 0xa6a32a, 0x4, 0xc42017b800, 0x1761, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/hookit/hookit.go:48 +0x3cd
github.com/nanobox-io/nanobox/util/hookit.DebugExec(0xc4201d6240, 0x40, 0xa6b20b, 0x5, 0xa698fe, 0x2, 0xa6a32a, 0x4, 0xc42017b800, 0x1761, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/hookit/hookit.go:54 +0x9e
github.com/nanobox-io/nanobox/processors/code.prepareBuildEnvironment(0xc4201d6240, 0x40, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/code/build.go:118 +0xa31
github.com/nanobox-io/nanobox/processors/code.Build(0xc42034c0b0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/code/build.go:46 +0x260
github.com/nanobox-io/nanobox/processors.Build(0xc42034c0b0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/build.go:30 +0x94
github.com/nanobox-io/nanobox/commands.buildFn(0xf3fc60, 0xc420251cc0, 0x1, 0x2)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/build.go:39 +0x47
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0xf3fc60, 0xc420251cc0, 0x1, 0x2)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:20 +0x12c
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0xf3fc60, 0xc420251ba0, 0x2, 0x2, 0xf3fc60, 0xc420251ba0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x41c
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf3d060, 0x0, 0x0, 0x1)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x3a4
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0xf3d060, 0xa97cb8, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x2b
main.main()
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:123 +0x4ef
2017-08-28 08:46:09 INFO  notifying bugsnag: panic
2017-08-28 08:46:09 FATAL Cause of failure: runtime error: invalid memory address or nil pointer dereference
2017-08-28 08:46:09 FATAL Error output:
goroutine 1 [running]:
runtime/debug.Stack(0xc420192cb0, 0x9c90c0, 0xf33fd0)
    /home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/debug/stack.go:24 +0x79
main.main.func1()
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:106 +0x71
panic(0x9c90c0, 0xf33fd0)
    /home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/nanobox-io/nanobox/util/hookit.Exec(0xc4201d6240, 0x40, 0xa6b20b, 0x5, 0xa698fe, 0x2, 0xa6a32a, 0x4, 0xc420126000, 0xabfb, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/hookit/hookit.go:25 +0x4b
github.com/nanobox-io/nanobox/util/hookit.DebugExec(0xc4201d6240, 0x40, 0xa6b20b, 0x5, 0xa698fe, 0x2, 0xa6a32a, 0x4, 0xc42017b800, 0x1761, ...)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/util/hookit/hookit.go:65 +0x1ac
github.com/nanobox-io/nanobox/processors/code.prepareBuildEnvironment(0xc4201d6240, 0x40, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/code/build.go:118 +0xa31
github.com/nanobox-io/nanobox/processors/code.Build(0xc42034c0b0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/code/build.go:46 +0x260
github.com/nanobox-io/nanobox/processors.Build(0xc42034c0b0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/build.go:30 +0x94
github.com/nanobox-io/nanobox/commands.buildFn(0xf3fc60, 0xc420251cc0, 0x1, 0x2)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/build.go:39 +0x47
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0xf3fc60, 0xc420251cc0, 0x1, 0x2)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:20 +0x12c
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0xf3fc60, 0xc420251ba0, 0x2, 0x2, 0xf3fc60, 0xc420251ba0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x41c
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf3d060, 0x0, 0x0, 0x1)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x3a4
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0xf3d060, 0xa97cb8, 0x0)
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x2b
main.main()
    /home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:123 +0x4ef
2017-08-28 08:46:09 *LOG* Closing log now
```

**Comment by glinton** [comment]
As a workaround, to get into the container, use `nanobox-machine ssh nanobox` then `docker exec -it <ID> bash` after the failure.

**Comment by glinton** [comment]
Looks like I broke `--debug` by capturing hook stream output. This regression fix is nearly complete.
