### ISSUE TITLE
Failed to Run nanobox deploy from within Container

### ISSUE THREAD

**Issue by xdays** [nanobox-io/nanobox#672]
we run nanobox from within docker:dind, and see the following error:

```
$ docker run --name dind -d  --rm --privileged -v $PWD:/opt/jarvis docker:dind
$ docker exec -it dind sh
/opt/jarvis # apk add --no-cache curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libssh2 (1.8.0-r2)
(2/3) Installing libcurl (7.61.0-r0)
(3/3) Installing curl (7.61.0-r0)
Executing busybox-1.27.2-r11.trigger
OK: 17 MiB in 41 packages
/opt/jarvis # export NANOBOX_USERNAME=foo
/opt/jarvis # export NANOBOX_PASSWORD=bar
/opt/jarvis # curl -so - https://d1ormdui8qdvue.cloudfront.net/installers/v2/lin
ux/nanobox-2.tar.gz | tar xzf - -C /
/opt/jarvis # nanobox config set ci-mode true
Successfully set 'ci-mode'
/opt/jarvis # nanobox config set provider native
Successfully set 'provider'
/opt/jarvis # nanobox remote add jarvis-staging

✓ You've successfully logged in

✓ Codebase linked to jarvis-staging

/opt/jarvis # nanobox -v deploy
Nanobox encountered an unexpected error. Please see ~/.nanobox/nanobox.log and submit the issue to us.
/opt/jarvis # cat ~/.nanobox/nanobox.log
2018-08-03 01:51:53 FATAL Cause of failure: runtime error: slice bounds out of range
2018-08-03 01:51:53 FATAL Error output:
goroutine 1 [running]:
runtime/debug.Stack(0xc4201a9980, 0x9bde80, 0xdb1e30)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
main.main.func1()
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:108 +0x6e
panic(0x9bde80, 0xdb1e30)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/nanobox-io/nanobox/util/service.Stop(0xa67cef, 0xb, 0x882800, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/service/stop_unix.go:12 +0x1c4
github.com/nanobox-io/nanobox/processors/server.Setup(0xc4201a9ba0, 0x925188)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/server/setup.go:27 +0x71
github.com/nanobox-io/nanobox/processors.Start(0x0, 0x10000c4200bdb00)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/start.go:11 +0x22
github.com/nanobox-io/nanobox/commands.startFn(0xdbc0a0, 0xc4202e2020, 0x0, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/start.go:31 +0x22
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0xdbc0a0, 0xc4202e2020, 0x0, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:19 +0x11b
github.com/nanobox-io/nanobox/commands.glob..func3(0xdbc0a0, 0xc4202e2020, 0x0, 0x1)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/deploy.go:30 +0xed
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0xdbc0a0, 0xc4202e2010, 0x1, 0x1, 0xdbc0a0, 0xc4202e2010)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x41b
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xdbb2a0, 0xc4201a9e60, 0xc4201a9e68, 0xffffffffffffffff)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x368
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0xdbb2a0, 0xa93240, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x2b
main.main()
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:121 +0x476

2018-08-03 01:51:53 *LOG* Closing log now
```

BTW, image docker:dind is built from alpine.

**Comment by danhunsaker** [comment]
Running Nanobox from within a Docker container, of any kind, is not supported. Docker-in-Docker is a pain to implement, among other reasons.
