### ISSUE TITLE
Vagrant error on windows

### ISSUE THREAD

**Issue by iiegor** [nanobox-io/nanobox#68]
### Steps to reproduce
- Run ``$ nanobox run`` or ``$ nanobox dev`` 

Using **Windows 7** SP1

### Error stack
```
2015-11-19 22:59:35 ERROR c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:587:in `read': El sistema no puede encontrar el archivo especificado. (Win32::Registry::Error)
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:647:in `read_s_expand'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/resolv.rb:55:in `block in get_hosts_dir'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:389:in `open'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:496:in `open'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/resolv.rb:54:in `get_hosts_dir'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/resolv.rb:14:in `get_hosts_path'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/resolv.rb:170:in `<class:Hosts>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/resolv.rb:167:in `<class:Resolv>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/resolv.rb:37:in `<top (required)>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:6:in `<top (required)>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:1:in `<top (required)>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:3:in `<top (required)>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:87:in `<class:LockfileParser>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:14:in `<module:Bundler>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:13:in `<top (required)>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:1:in `<top (required)>'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:155:in `definition'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:123:in `setup'
2015-11-19 22:59:35 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:71:in `<main>'
2015-11-19 22:59:35 FATAL [commands/create] vagrant.Up() failed -  - exit status 1
2015-11-19 22:59:35 *LOG* Closing log now
2015-11-19 23:00:25 ERROR c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:587:in `read': El sistema no puede encontrar el archivo especificado. (Win32::Registry::Error)
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:647:in `read_s_expand'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/resolv.rb:55:in `block in get_hosts_dir'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:389:in `open'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/registry.rb:496:in `open'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/resolv.rb:54:in `get_hosts_dir'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/win32/resolv.rb:14:in `get_hosts_path'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/resolv.rb:170:in `<class:Hosts>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/resolv.rb:167:in `<class:Resolv>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/resolv.rb:37:in `<top (required)>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:6:in `<top (required)>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:1:in `<top (required)>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:3:in `<top (required)>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:87:in `<class:LockfileParser>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:14:in `<module:Bundler>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/lockfile_parser.rb:13:in `<top (required)>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:1:in `<top (required)>'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:155:in `definition'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:123:in `setup'
2015-11-19 23:00:25 ERROR 	from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:71:in `<main>'
2015-11-19 23:00:26 FATAL [commands/create] vagrant.Up() failed -  - exit status 1
2015-11-19 23:00:26 *LOG* Closing log now

```

**Comment by imkheong** [comment]
Had a similar issue. 
First, I add PATH by set PATH=%PATH%;c:\Pagoda Box\nanobox;C:\HashiCorp\Vagrant\bin;C:\Program Files\Oracle\VirtualBox.

After which I tried the command `nanobox dev`, which proceed to download and install nanobox/boot2docker.

After which it attempts to Create a nanobox

And then it fails
A fatal error occurred (See ~/.nanobox/nanobox.log for details). Exiting...

Looking in nanobox.log, it says 
2015-11-24 10:00:28 FATAL [commands/create] vagrant.Up() failed -  - exit status 1
2015-11-24 10:00:28 *LOG* Closing log now

Any thoughts what might be wrong here?

**Comment by glinton** [comment]
@imkheong when you see that 'vagrant.Up() failed - - exit status 1' error again, can you paste the output of `~/.nanobox/apps/<APPNAME>/vagrant.log`? It will have much more useful infomation regarding this issue. Thanks.

Also, there is a new nanobox binary you should try (update by running `nanobox update`) that has some improvements for running on windows.

**Comment by tylerflint** [comment]
@imkheong Any update on this?

**Comment by imkheong** [comment]
@glinton @tylerflint sorry for the delay. Here goes the vagrant.log.

2015-11-24 10:00:28 ERROR There is a syntax error in the following Vagrantfile. The syntax error
2015-11-24 10:00:28 ERROR message is reproduced below for convenience:
2015-11-24 10:00:28 ERROR 2015-11-24 10:00:28 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:61: syntax error, unexpected tIDENTIFIER, expecting keyword_end
2015-11-24 10:00:28 ERROR ...uest: 22, host: 11927, id: 'ssh'
2015-11-24 10:00:28 ERROR ...                               ^
2015-11-24 10:00:28 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:94: syntax error, unexpected tIDENTIFIER, expecting keyword_end
2015-11-24 10:00:28 ERROR ... dhcp server so that it doesn't override the assigned ip when
2015-11-24 10:00:28 ERROR ...                               ^
2015-11-24 10:00:28 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:94: syntax error, unexpected keyword_when, expecting keyword_end
2015-11-24 10:00:28 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:106: syntax error, unexpected keyword_end, expecting end-of-input
2015-11-24 10:10:25 ERROR There is a syntax error in the following Vagrantfile. The syntax error
2015-11-24 10:10:25 ERROR message is reproduced below for convenience:
2015-11-24 10:10:25 ERROR 2015-11-24 10:10:25 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:61: syntax error, unexpected tIDENTIFIER, expecting keyword_end
2015-11-24 10:10:25 ERROR ...uest: 22, host: 11927, id: 'ssh'
2015-11-24 10:10:25 ERROR ...                               ^
2015-11-24 10:10:25 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:94: syntax error, unexpected tIDENTIFIER, expecting keyword_end
2015-11-24 10:10:25 ERROR ... dhcp server so that it doesn't override the assigned ip when
2015-11-24 10:10:25 ERROR ...                               ^
2015-11-24 10:10:25 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:94: syntax error, unexpected keyword_when, expecting keyword_end
2015-11-24 10:10:25 ERROR C:/Users/user.name/.nanobox/apps/Vagrantfile:106: syntax error, unexpected keyword_end, expecting end-of-input
