### ISSUE TITLE
Can't get mount type netfs to work on Windows 10

### ISSUE THREAD

**Issue by jamesmacwhite** [nanobox-io/nanobox#696]
I've used nanobox for a while but have never been able to get the `netfs` mount type working, despite all the recommendations of messing around with file sharing, public/private networks etc. Frankly, I just gave up and set the `mount-type` to `native` and left it, however the performance is something I am a bit bothered about so I'm trying to figure out why it nanobox can't use `netfs`.

This is the error I get after several mount attempts when running `nanobox run`

```
2019-03-23 15:46:48 DEBUG https://api.nanobox.io/v1/events?api_key=REDACTED&auth_token=REDACTED
2019-03-23 15:46:50 DEBUG RES: 200 POST https://api.nanobox.io/v1/events?api_key=REDACTED&auth_token=REDACTED HTTP/1.1 ()
2019-03-23 15:47:45 INFO  adding share in netfs for C:/Users/james.white/Projects/nottinghamcollege-marketing_site-craft3
2019-03-23 15:47:45 DEBUG net share output: 
Share name   Resource                        Remark

-------------------------------------------------------------------------------
C$           C:\                             Default share                     
IPC$                                         Remote IPC                        
print$       C:\WINDOWS\system32\spool\drivers
                                             Printer Drivers                   
ADMIN$       C:\WINDOWS                      Remote Admin                      
nanobox-8a720a6e7e1bc4060a4927a07476855d
             C:/Users/james.white/Projects/nottinghamcollege-marketing_site-craft3
                                             
The command completed successfully.

2019-03-23 15:47:45 DEBUG output contains path: C:/Users/james.white/Projects/nottinghamcollege-marketing_site-craft3
2019-03-23 15:47:45 INFO  adding mount in for netfs C:/Users/james.white/Projects/nottinghamcollege-marketing_site-craft3 -> /share/8a720a6e7e1bc4060a4927a07476855d/code
2019-03-23 15:48:20 DEBUG cifs mount cmd: [sudo /bin/mount -t cifs -o mfsymlinks,nodev,sec=ntlmssp,user='james.white',password='*************',uid=1000,gid=1000 //192.168.99.1/nanobox-8a720a6e7e1bc4060a4927a07476855d /share/8a720a6e7e1bc4060a4927a07476855d/code]
2019-03-23 15:48:31 DEBUG mount output: mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //192.168.99.1/nanobox-8a720a6e7e1bc4060a4927a07476855d on /share/8a720a6e7e1bc4060a4927a07476855d/code failed: Host is down
exit status 32
2019-03-23 15:48:31 ERROR mount: output: mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //192.168.99.1/nanobox-8a720a6e7e1bc4060a4927a07476855d on /share/8a720a6e7e1bc4060a4927a07476855d/code failed: Host is down
exit status 32
 err:exit status 1
2019-03-23 15:48:31 ERROR goroutine 1 [running]:
runtime/debug.Stack(0xc042438240, 0x119, 0x0)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/debug/stack.go:24 +0xae
github.com/nanobox-io/nanobox/util.Err.log(0x0, 0x0, 0xc042438240, 0x119, 0x0, 0x0, 0xe57358, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:38 +0xe5
github.com/nanobox-io/nanobox/util.ErrorQuiet(0xde44a0, 0xc042280030, 0x463849, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:95 +0x244
github.com/nanobox-io/nanobox/util.Error(0xde44a0, 0xc042280030, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:105 +0x60
github.com/nanobox-io/nanobox/util.ErrorAppend(0xde44a0, 0xc042280030, 0xacfe28, 0x2e, 0x0, 0x0, 0x0, 0x0, 0xc042179438)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/error.go:128 +0x385
github.com/nanobox-io/nanobox/processors/env.Mount(0xc0424aa0b0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/mount.go:46 +0x26e
github.com/nanobox-io/nanobox/processors/env.Setup.func1(0x41115f, 0x10)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/setup.go:107 +0x31
github.com/nanobox-io/nanobox/util.Retry(0xc042280020, 0x5, 0x2540be400, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/retry.go:12 +0x8b
github.com/nanobox-io/nanobox/processors/env.Setup(0xc0424aa0b0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/processors/env/setup.go:110 +0xc3f
github.com/nanobox-io/nanobox/commands/dev.devStart(0xe2b200, 0xc0422d16c0, 0x1, 0x2)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/dev/start.go:27 +0x73
github.com/nanobox-io/nanobox/commands/steps.Run.func1(0xe2b200, 0xc0422d16c0, 0x1, 0x2)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/commands/steps/run.go:19 +0x122
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).execute(0xe2b200, 0xc0422d1560, 0x2, 0x2, 0xe2b200, 0xc0422d1560)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:561 +0x422
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe28600, 0xc0421a1e60, 0xc0421a1e68, 0xffffffffffffffff)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:656 +0x36f
github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra.(*Command).Execute(0xe28600, 0xae2c68, 0xe57358)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/vendor/github.com/spf13/cobra/command.go:615 +0x32
main.main()
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/main.go:121 +0x47d
```
My Windows host is connected to a Active Directory domain so I don't know if that might have something to do with it. I also have SMB 1.0 disabled, since Windows 10 does this by default in newer versions.

Can anyone provide any guidance on what needs to be in place for a Windows environment to work using netfs with Nanobox?

**Comment by jamesmacwhite** [comment]
Looks like nanobox can only mount shares using SMB1. Microsoft disabled SMB1 support in Windows 10 build 1709 and above.

https://support.microsoft.com/en-gb/help/4034314/smbv1-is-not-installed-by-default-in-windows

So you need to re-enable SMB1:

https://support.microsoft.com/en-us/help/2696547/detect-enable-disable-smbv1-smbv2-smbv3-in-windows-and-windows-server

I have tried to force the SMB version with `vers=2.0`, `vers=3.0` and `vers=3.02` as additional mount opts but it seems Nanobox doesn't support anything higher.
